---
- name: zips files older than 10 days
  hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: "Zip /var/log"
      shell: "find /var/log/ -type f -name  '\"*log*\"'  -atime +10 -exec gzip {} \\;"