---
- name: create centos 7 instance 
  hosts: localhost
  tasks:
    - name: create Centos 7 VM
      ec2:
        key_name: towerCentOS
        instance_type: t2.micro
        image: ami-0f2b4fc905b0bd1f1
        count: 3
        region: us-east-2
        vpc_subnet_id: subnet-4f85ff35
        assign_public_ip: yes
