---
- name: helps download files 
  hosts: all
  become: yes
  become_method: sudo
  vars_prompt: 
    - name: URL
      prompt: "give me a url"
      private: no 
  tasks: 
    - name: download 1 package
      get_url:
        url: "{{URL}}"
        dest: /tmp/