---
- name: helps download files 
  vars_prompt: 
    - name: URL
      prompt: "give me a url"
      private: no 
    - name: DESTINATION
      prompt: "give me a destination to download to"
      private: no
    - name: HOST
      prompt: "which host ?"
      private: no
  hosts: localhost
  become: yes
  become_method: sudo
  tasks: 
    - name: download 1 package
      get_url:
        url: "{{URL}}"
        dest: "{{DESTINATION}}"