---
- name: creates ec2 instances
  hosts: localhost
  vars_files: 
    - ec2_vars
  tasks:
    - name: create instances 
      ec2:
        key_name: "{{key_name}}"
        instance_type: "{{instance_type}}"
        image: "{{image}}"
        count: "{{count}}"
        vpc_subnet_id: "{{vpc_subnet_id}}"
        region: "{{region}}"
        #user_data: "{{ lookup('file', 'user_date.sh')}}"
        assign_public_ip: yes



