---
- hosts: web
  name: install software
  become: yes
  become_method: sudo
  tasks: 
    - name: install httpd
      package:
        name: httpd
        state: latest
    - name: restart httpd.service
      systemd: 
        name: httpd
        state: restarted
        enabled: yes
      become: yes
      become_method: sudo
