---
- hosts: 
    ec2-18-218-6-44.us-east-2.compute.amazonaws.com
  tasks:
    - name: install 1 package
      package:
        name: httpd
        state: latest
      become: yes
      become_method: sudo