---
- hosts: php
  name: php 5.6
  become: yes
  become_method: sudo
  tasks:
    - name: update php
      shell: |
        yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm
        yum install yum-utils
        yum-config-manager --enable remi-php56   [Install PHP 5.6]
        yum install php php-mcrypt php-cli php-gd php-curl php-mysql php-ldap php-zip php-fileinfo
        