---
- hosts: php
  name: php update
  become: yes
  become_method: sudo
  tasks:
    - name: epel release
      shell: "sudo yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    - name: remi
      shell: "sudo yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    - name: config manager enable
      shell: "sudo yum-config-manager --enable remi-php56"
    - name: update httpd php
      shell: "sudo yum update httpd php php-mysql mysql"