---
- hosts: web
  name: install remi and epel repo from remote 
  tasks:
    yum: 
      name: 
      - "{{ http://rpms.remirepo.net/enterprise/remi-release-6.rpm }}"
      - "{{ https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm }}"
    become: true 
    
    name: get remi key
    get_url: 
    - url: "{{ http://rpms.remirepo.net/RPM-GPG-KEY-remi }}" 
    - dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-remi
    become: true 

    name: install php7 packages 
    yum:
      name:
      - php
      - nginx
      - php-fpm
      - php-mysql
      - php-pdo
      - php-mbstring
      - php-xml
      - php-gd
      nablerepo: "remi-{{ php72 }},epel"
    become: true