---
- hosts: php
  name: php update
  become: yes
  become_method: sudo
  tasks:
    - name: epel release
      shell: "sudo wget -q http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    - name: config manager enable
      shell: "sudo yum-config-manager --enable remi-php70"
    - name: update httpd php
      shell: "sudo yum update httpd php php-mysql mysql"