---
- hosts: web
  vars:
    php_version: php72
    remi_release_url: "http://rpms.remirepo.net/enterprise/remi-release-6.rpm"
    epel_release_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm"
    remi_key_url: "http://rpms.remirepo.net/RPM-GPG-KEY-remi"
  name: install remi and epel repo from remote 
  tasks:
    yum: 
      name: 
      - "{{ remi_release_url }}"
      - "{{ epel_release_url }}"
    become: true 
    
    name: get remi key
    get_url: 
    - url: "{{ remi_key_url }}" 
    - dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-remi
    become: true 

    name: install php7 packages 
    yum:
      name:
      - php
      - nginx
      - php-fpm
      - php-mysql
      - php-pdo
      - php-mbstring
      - php-xml
      - php-gd
      nablerepo: "remi-{{ php_version }},epel"
    become: true