---
- name: User Management
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: Add multiple users to the system
      user:
        name: "{{item}}"
        state: present
      with_items:
        - bob
        - lisa
        - kenny
        - ben
