---
- hosts: web
  name: install wordpress
  gather_facts: no
  connection: ssh
  become: yes
  become_method: sudo
  tasks: 
    - name: install relevant packages
      package: 
        name: "{{item}}"
        state: latest
      with_items:
        - wget 
        - unzip 
        - php-gd
        - httpd 
        - mysql 
        - mariadb
        - php 
        - php-mysql
        - php-fpm
        enablerepo: "remi-{{ php72 }},epel"
      ignore_errors: true 
    
    - name: download 1 package
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: /tmp/
      
    - name: unzip wordpress file
      unarchive: 
        src: "/tmp/wordpress-5.2.1.tar.gz"
        dest: /var/www/html/
        remote_src: yes
      become: yes
      become_method: sudo 

    - name: move files to html folder
      shell: "mv /var/www/html/wordpress/* /var/www/html"
      become: yes
      become_method: sudo
      ignore_errors: yes   

    - name: restart httpd.service
      systemd: 
        name: httpd
        state: started
        enabled: yes
      become: yes
      become_method: sudo
    
    - name: remi and epel
      yum: 
        name: 
        - "{{ http://rpms.remirepo.net/enterprise/remi-release-6.rpm }}"
        - "{{ https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm }}"
      become: true 
    
    - name: get remi key
      get_url: 
      - url: "{{ http://rpms.remirepo.net/RPM-GPG-KEY-remi }}" 
      - dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-remi
      become: true 

    - name: install php7 packages 
      yum:
        name:
        - php
        - nginx
        - php-fpm
        - php-mysql
        - php-pdo
        - php-mbstring
        - php-xml
        - php-gd
        enablerepo: "remi-{{ php72 }},epel"
      become: true


