---
- hosts: php
  name: install wordpress
  become: yes
  become_method: sudo
  tasks: 
    - name: install relevant packages
      package: 
        name: "{{item}}"
        state: latest
      with_items:
        - wget 
        - unzip 
        - php-gd
        - httpd 
        - mysql 
        - mariadb
        - php 
        - php-mysql
        - php-fpm
      ignore_errors: true 

    - name: epel release
      shell: "sudo wget -q http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    
    - name: config manager enable
      shell: "sudo yum-config-manager --enable remi-php70"
    
    - name: update httpd php
      shell: "sudo yum update httpd php php-mysql mysql"

    - name: download 1 package
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: /tmp/
      
    - name: unzip wordpress file
      unarchive: 
        src: "/tmp/wordpress-5.2.1.tar.gz"
        dest: /var/www/html/
        remote_src: yes
      become: yes
      become_method: sudo 

    - name: move files to html folder
      shell: "mv /var/www/html/wordpress/* /var/www/html"
      become: yes
      become_method: sudo
      ignore_errors: yes   

    - name: restart httpd.service
      systemd: 
        name: httpd
        state: started
        enabled: yes
      become: yes
      become_method: sudo
    
