---
- hosts: localhost
  name: install wordpress
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh
  tasks: 
    - name: install relevant packages
      package: 
        name: "{{item}}"
        state: latest
      with_items:
        - wget 
        - unzip 
        - php-gd
        - httpd 
        - mysql 
        - mariadb
        - php 
        - php-mysql
        - php-fpm
      ignore_errors: true 

    - name: download 1 package
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: /tmp/
      
    - name: unzip wordpress file
      unarchive: 
        src: "/tmp/latest.tar.gz"
        dest: /var/www/html/wordpress 
        remote_src: yes
      become: yes
      become_method: sudo 

    - name: move files to html folder
      shell: "mv /var/www/html/wordpress/* /var/www/html"
      become: yes
      become_method: sudo
      ignore_errors: yes   

    - name: restart httpd.service
      systemd: 
        name: httpd
        state: restarted
        enabled: yes
      become: yes
      become_method: sudo


