--- 
- name: delete the s3 bucket you created
  hosts: localhost
  vars_files: 
   - bucketCreds
  tasks:
    - name: delete an s3 bucket
      aws_s3:
       aws_access_key: "{{ access_key }}"
       aws_secret_key: "{{ secret_key }}"
       bucket: "{{ bucketname }}"
       mode: delete 
      