---
- hosts: web
  name: install wordpress
  gather_facts: no
  connection: ssh
  become: yes
  become_method: sudo
  tasks: 
    - name: install relevant packages
      yum: use_backend
        name: 
          - wget 
          - unzip 
          - php-gd
          - httpd 
          - mysql 
          - mariadb
          - php 
          - php-mysql
          - php-fpm
        state: latest
    
    - name: download 1 package
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: /tmp/
      
    - name: unzip wordpress file
      unarchive: 
        src: "/tmp/wordpress-5.2.1.tar.gz"
        dest: /var/www/html/
        remote_src: yes
      become: yes
      become_method: sudo 

    - name: move files to html folder
      shell: "mv /var/www/html/wordpress/* /var/www/html"
      become: yes
      become_method: sudo
      ignore_errors: yes   

    - name: restart httpd.service
      systemd: 
        name: httpd
        state: restarted
        enabled: yes
      become: yes
      become_method: sudo


